GemWallet/gemwallet-extension

packages/api/src/isConnected.ts
Make isConnected work if extension is not installed
=> Make isConnected work if extension is not installed

CONTRIBUTING.md, README.md
Add contributing files including:
- How to contribute
- Code of conduct
=> Add Contributing file

packages/extension/package.json, packages/extension/src/components/atoms/TileLoader/TileLoader.tsx, packages/extension/src/components/atoms/TileLoader/index.ts, packages/extension/src/components/atoms/index.ts, packages/extension/src/components/molecules/Wallet/Wallet.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, yarn.lock
- Add TileLoader
- Replace `Loading...` string with a Loading component.
=> Add TileLoader

packages/extension/src/App.tsx, packages/extension/src/components/atoms/PrivateRoute/PrivateRoute.tsx, packages/extension/src/components/atoms/TileLoader/TileLoader.tsx, packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx, packages/extension/src/components/molecules/TextCopy/TextCopy.tsx, packages/extension/src/components/molecules/TextCopy/TextCopy.types.ts, packages/extension/src/components/molecules/Wallet/Wallet.tsx, packages/extension/src/components/molecules/Wallet/Wallet.types.tsx, packages/extension/src/components/organisms/Drawer/AboutPage.tsx, packages/extension/src/components/organisms/Drawer/Drawer.tsx, packages/extension/src/components/organisms/Drawer/DrawerContent.tsx, packages/extension/src/components/organisms/Navbar/Navbar.tsx, packages/extension/src/components/organisms/Transaction/Transaction.tsx, packages/extension/src/components/organisms/Transaction/Transaction.types.ts, packages/extension/src/components/pages/CreateWallet/CreateWallet.tsx, packages/extension/src/components/pages/Home/Home.tsx, packages/extension/src/components/pages/ImportSeed/ImportSeed.tsx, packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/components/pages/ResetPassword/ResetPassword.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/components/pages/Welcome/Welcome.tsx, packages/extension/src/components/templates/ErrorBoundary/ErrorBoundary.tsx, packages/extension/src/components/templates/PageWithNavbar/PageWithNavbar.tsx, packages/extension/src/components/templates/PageWithNavbar/PageWithNavbar.types.ts, packages/extension/src/components/templates/PageWithReturn/PageWithReturn.tsx, packages/extension/src/components/templates/PageWithStepper/PageWithStepper.tsx, packages/extension/src/contexts/BrowserContext/BrowserContext.tsx, packages/extension/src/contexts/DrawerContext/DrawerContext.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
=> Cleanup types and interface

packages/extension/src/components/molecules/Wallet/Wallet.test.tsx, packages/extension/src/components/molecules/Wallet/Wallet.tsx
1. Display only the funds in XRP on the home page after the new Menu
=> Display only the funds in XRP on the home page after the new Menu

packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx, packages/extension/src/utils/crypto.test.ts, packages/extension/src/utils/crypto.ts, packages/extension/src/utils/wallet.ts
=> Inform the user when the password is wrong

packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
- [Disconnect to the ledger before the extension closes](https://github.com/GemWallet/gemwallet-extension/commit/3f873c5e219776bcc73f9ff3cafa690b50d43d1f)
=> Disconnect to the ledger before the extension closes

packages/extension/src/components/atoms/IconTextButton/IconTextButton.tsx, packages/extension/src/components/atoms/IconTextButton/index.ts, packages/extension/src/components/atoms/TokenLoader/TokenLoader.tsx, packages/extension/src/components/atoms/TokenLoader/index.ts, packages/extension/src/components/atoms/Tokens/Xrp/Xrp.tsx, packages/extension/src/components/atoms/Tokens/Xrp/index.ts, packages/extension/src/components/atoms/Tokens/index.ts, packages/extension/src/components/atoms/index.ts, packages/extension/src/components/molecules/InformationMessage/InformationMessage.tsx, packages/extension/src/components/molecules/InformationMessage/index.ts, packages/extension/src/components/molecules/TokenDisplay/TokenDisplay.tsx, packages/extension/src/components/molecules/TokenDisplay/index.ts, packages/extension/src/components/molecules/Wallet/Wallet.tsx, packages/extension/src/components/molecules/index.ts, packages/extension/src/components/organisms/Header/Header.tsx, packages/extension/src/components/pages/About/About.tsx, packages/extension/src/components/pages/CreateWallet/SecretSeed/SecretSeed.tsx, packages/extension/src/components/pages/Home/Home.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/constants/index.ts, packages/extension/src/constants/tokens.ts, packages/extension/src/utils/format.test.ts, packages/extension/src/utils/format.ts
1. Improve the token display by showing an icon
2. Improve the token loader
3. Add information message about reserve amount
4. Edit about section to inform user than GemWallet is non-custodial
5. Add explain button near the token
6. Improve molecule imports
7. Create Tokens ENUM
=> Add Reserve Amount information

packages/extension/src/components/organisms/Transaction/Transaction.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Handle errors if address does not exist:
- checksum_invalid
- version_invalid
- tecNO_DST_INSUF_XRP
=> Add errors when address does not exist

packages/constants/src/payload/payload.types.ts, packages/extension/src/components/pages/SignMessage/SignMessage.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx
- [Fix return type for Transaction and SignMessage](https://github.com/GemWallet/gemwallet-extension/commit/57e075e7c82a5fb6b8656de8d4b2a95efa017995)
=> Fix return type for Transaction and SignMessage

.vscode/settings.json, packages/extension/src/components/organisms/NavMenu/NavMenu.tsx, packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/components/pages/Settings/Settings.tsx, packages/extension/src/components/pages/TrustedApps/TrustedApps.tsx, packages/extension/src/components/templates/PageWithNavMenu/PageWithNavMenu.tsx, packages/extension/src/index.css, packages/extension/src/index.tsx
On non-dark mode browsers the scroll bar was too much visible. This is now fixed.
Commits:
- [Fix issues with scroll bars on non-dark mode browsers](https://github.com/GemWallet/gemwallet-extension/commit/9bb4c82b7d6b48aabeb52a444084c2df2809ceb9)
=> Fix issues with scroll bars on non-dark mode browsers

packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx, packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/components/pages/TrustedApps/TrustedApps.tsx, packages/extension/src/components/templates/LoadingOverlay/LoadingOverlay.tsx, packages/extension/src/components/templates/LoadingOverlay/index.ts, packages/extension/src/components/templates/index.ts
Here are some UX improvements after the first release to the Chrome store (2.0.0)
Commits:
- [Resolve issue with incorrect JSON on login page](https://github.com/GemWallet/gemwallet-extension/commit/edf5f6f2f934bebbdc0468b945ab45c98a742663)
- [Add information about no trusted apps if none](https://github.com/GemWallet/gemwallet-extension/commit/3b40ebd8336a7b207a9e7924b244a8648bedb95c)
- [Add a spinner when changing network](https://github.com/GemWallet/gemwallet-extension/commit/8cb723be72188dc35f62b5e279a566a8e74b1f90)
=> Feat/ux improvements 2.0.0

README.md, packages/extension/package.json, packages/extension/public/manifest.json
Commits:
- [Bump packages for the release 2.1.0](https://github.com/GemWallet/gemwallet-extension/commit/955f3c42f1ce31d2af837606e40143c9bbb611c3)
=> Bump packages for the release 2.1.0

packages/extension/package.json, packages/extension/src/App.tsx, packages/extension/src/components/pages/Congratulations/Congratulations.tsx, packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx, packages/extension/src/components/pages/CreateWallet/ConfirmSeed/ConfirmSeed.tsx, packages/extension/src/components/pages/CreateWallet/SecretSeed/SecretSeed.tsx, packages/extension/src/components/pages/ImportMnemonic/Mnemonic/Mnemonic.tsx, packages/extension/src/components/pages/ImportSecretNumbers/ImportSecretNumbers.test.tsx, packages/extension/src/components/pages/ImportSecretNumbers/ImportSecretNumbers.tsx, packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/SecretNumbers.test.tsx, packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/SecretNumbers.tsx, packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/index.ts, packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/styles.module.css, packages/extension/src/components/pages/ImportSecretNumbers/index.ts, packages/extension/src/components/pages/ImportSeed/SecretSeed/SecretSeed.tsx, packages/extension/src/components/pages/ImportWallet/ImportWallet.tsx, packages/extension/src/components/pages/index.ts, packages/extension/src/components/templates/PageWithStepper/PageWithStepper.tsx, packages/extension/src/constants/routes.ts, packages/extension/src/contexts/WalletContext/WalletContext.tsx, packages/extension/src/mocks/walletContext.ts, yarn.lock
Now users can import wallet with secret numbers
Commits:
- [Import wallet with secret numbers](https://github.com/GemWallet/gemwallet-extension/commit/8837162126f28647fb1b402ef49c8c52e1fa75e8)
=> Import wallet with secret numbers

packages/api/releaseNpm.js, packages/api/src/sendPayment/sendPayment.test.ts, packages/api/templates/index.html, packages/extension/src/App.tsx, packages/extension/src/chromeServices/background.ts, packages/extension/src/chromeServices/content.ts, packages/extension/src/components/atoms/ButtonOption/ButtonOption.test.tsx, packages/extension/src/components/atoms/WalletIcon/WalletIcon.test.tsx, packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.test.tsx, packages/extension/src/components/pages/ShareAddress/ShareAddress.tsx, packages/extension/src/components/pages/SharePublicKey/SharePublicKey.tsx, packages/extension/src/components/pages/SignMessage/SignMessage.tsx, packages/extension/src/reportWebVitals.ts, packages/extension/src/utils/breakStringByLine.test.ts, packages/extension/src/utils/crypto.test.ts, packages/extension/src/utils/link.test.ts, packages/extension/src/utils/network.test.ts, packages/extension/src/utils/network.ts, packages/extension/src/utils/storage.ts, packages/extension/src/utils/wallet.test.ts
=> Code improvement

packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.test.tsx, packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx, packages/extension/src/components/organisms/WalletDetail/WalletDetail.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/constants/index.ts, packages/extension/src/constants/server.ts, packages/extension/src/contexts/NetworkContext/NetworkContext.tsx, packages/extension/src/contexts/ServerContext/ServerContext.test.tsx, packages/extension/src/contexts/ServerContext/ServerContext.tsx
Handling failed connection to websocket
Commits:
- [Handling failed connection to websocket](https://github.com/GemWallet/gemwallet-extension/commit/56eb8d10001a4a1deaae6b095395607de8985fc8)
=> Handling failed connection to websocket

packages/extension/cypress.config.ts, packages/extension/cypress/e2e/networks.cy.ts, packages/extension/cypress/e2e/wallet_management.cy.ts, packages/extension/cypress/fixtures/example.json, packages/extension/cypress/support/commands.ts, packages/extension/cypress/support/e2e.ts, packages/extension/cypress/tsconfig.json, packages/extension/package.json, packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx, packages/extension/src/components/pages/EditWallet/EditWallet.tsx, packages/extension/src/components/pages/ListWallets/ListWallets.tsx, packages/extension/src/components/templates/LoadingOverlay/LoadingOverlay.tsx, packages/extension/src/components/templates/PageWithReturn/PageWithReturn.tsx, yarn.lock
Add basic Cypress testing
Commits:
- [Add basic E2E](https://github.com/GemWallet/gemwallet-extension/commit/27fd1cd9b1e29cdca72e974ac1d1493274fe8710)
=> Add basic E2E

packages/extension/src/components/pages/AddNewWallet/ConfirmPassword/ConfirmPassword.tsx, packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportMnemonic/ImportMnemonic.tsx, packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportSeed/ImportSeed.tsx, packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx, packages/extension/src/components/pages/CreateWallet/ConfirmSeed/ConfirmSeed.tsx, packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx, packages/extension/src/components/pages/Login/Login.tsx, yarn.lock
Replace the getElementById by references.
Commits:
-[refactor document.getElementById to useRef<HTMLInputElement | null>(n…](https://github.com/GemWallet/gemwallet-extension/pull/87/commits/b218bdd5ccfa724260e1c36fe9f57d70e6db3f23)
=> refactor document.getElementById to useRef

packages/api/templates/index.html, packages/constants/src/payload/payload.types.ts, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Allow users to make transactions with other tokens
Commits:
- [Add transaction with other tokens](https://github.com/GemWallet/gemwallet-extension/commit/cee163446270411ccd87a1c9ecf170cb72b4cb5b)
=> Add transaction with other tokens

packages/extension/cypress/e2e/networks.cy.ts, packages/extension/cypress/e2e/payments.cy.ts, packages/extension/package.json, packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx, packages/extension/src/components/templates/PageWithTitle/PageWithTitle.tsx, yarn.lock
- Update Sentry
- Add the end to end tests for the payments
=> Add e2e testing for the payment

packages/extension/cypress/e2e/payments.cy.ts, packages/extension/cypress/e2e/trustlines.cy.ts
Add e2e tests for the trustlines
=> Add e2e testing for the trustlines

packages/extension/src/contexts/WalletContext/WalletContext.tsx
Makes sure that the selectedWallet is properly working
Commits:
- [Fix the loading of the selected wallet](https://github.com/GemWallet/gemwallet-extension/commit/cb079623d158358b8a83377ab23ebf893142e5a7)
=> Fix the loading of the selected wallet

packages/extension/package.json, packages/extension/src/App.tsx, packages/extension/src/components/organisms/TransactionListing/TransactionListing.mock.ts, packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx, packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx, packages/extension/src/components/organisms/TransactionListing/index.ts, packages/extension/src/components/organisms/index.ts, packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx, packages/extension/src/components/pages/History/History.tsx, packages/extension/src/components/pages/History/index.ts, packages/extension/src/components/pages/index.ts, packages/extension/src/components/templates/PageWithSpinner/PageWithSpinner.tsx, packages/extension/src/constants/navigation.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx, packages/extension/src/mocks/ledgerContext.ts, packages/extension/src/types/transaction.types.ts, yarn.lock
Allow users to see the history of their transactions
Commits:
- [Add Transaction history](https://github.com/GemWallet/gemwallet-extension/commit/a4456b481028157a68e5a07cfaab038d1a9aae9f)
=> Add Transaction history

package.json, packages/extension/cypress/e2e/wallet_management.cy.ts, packages/extension/package.json, packages/extension/src/components/pages/Transaction/Transaction.tsx
Makes sure that the estimation is done with the trustline information
Commits:
- [Improve the estimation of transaction fees for trustlines](https://github.com/GemWallet/gemwallet-extension/commit/74907ee2c0a5772799b960f238d3c3c712037137)
=> Improve the estimation of transaction fees for trustlines

packages/extension/src/components/organisms/TokenListing/TokenListing.tsx, packages/extension/src/utils/convertCurrencyString.test.ts, packages/extension/src/utils/convertCurrencyString.ts, packages/extension/src/utils/index.ts
Commits:
-[Decode hex tokens](https://github.com/GemWallet/gemwallet-extension/commit/3d4cee1f005b21c2f791aae415281098e88a5e3b)
=> Decode hex tokens

packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx
Fix UI glitch when showing the seed
Commits:
- [Fix UI glitch when show seed](https://github.com/GemWallet/gemwallet-extension/commit/2d6eb221a8d240bb25919d7bd57d9034f6bf89c9)
=> Fix UI glitch when show seed

packages/extension/cypress/e2e/wallet_management.cy.ts
Fix Cypress tests after resolving UI
=> Fix Cypress tests after resolving UI

packages/api/package.json, packages/extension/package.json, packages/extension/public/manifest.json
Commits:
- [Release 2.5.0](https://github.com/GemWallet/gemwallet-extension/commit/f32b99fd5faec0a27145da885c4a8a8844fb4770)
=> Release 2.5.0

packages/extension/src/chromeServices/background.ts
Cleanup the background service file
Commits:
- [Refactor background service](https://github.com/GemWallet/gemwallet-extension/commit/f75f6ba14de0d5391876fe5c33a3209eb2fcfe56)
=> Refactor background service

packages/api/releaseNpm.js, packages/api/src/index.ts
Expose types to GemWallet API and update the release script
Commits:
- [Fixup the releaseNpm script](https://github.com/GemWallet/gemwallet-extension/pull/112/commits/7fd533da39abd9eef0b4068ab1fc98570f6a574d)
- [Add missing types](https://github.com/GemWallet/gemwallet-extension/pull/112/commits/59310aae070c715700cb6de219140c5235a96b02)
=> Feat/expose types to API

packages/extension/src/components/organisms/TransactionListing/TransactionListing.mock.ts, packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx, packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx, packages/extension/src/index.css, packages/extension/src/types/transaction.types.ts
Allow to list the NFTs of the wallet via the API
Commits:
- [Added modal for displaying tx details](https://github.com/GemWallet/gemwallet-extension/pull/113/commits/a38f4380a919cb520bdf4778a84cddccc584ee94)
- [Minor bug fixes and font-family added](https://github.com/GemWallet/gemwallet-extension/pull/113/commits/23f32d24f2bf9d03ae0b4262896966a02d43a90f)
- [Merge remote-tracking branch 'upstream/master' into transaction-details](https://github.com/GemWallet/gemwallet-extension/pull/113/commits/ff0d7dec265105dff62d997ea107f0ed5da865d0)
- [Fixed Type error](https://github.com/GemWallet/gemwallet-extension/pull/113/commits/0cb1e95c65472acac39ce39e1760eddc13ebc88d)
=> Transaction details improvement

.github/workflows/integration.yml, package.json, packages/extension/cypress/e2e/networks.cy.ts, packages/extension/cypress/e2e/send_token.cy.ts, packages/extension/cypress/e2e/wallet_management.cy.ts, packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx
=> Add CI: Integration

packages/extension/src/components/pages/Login/Login.tsx
Autofocus the password field when the extension is opened
=> Autofocus password

packages/extension/cypress/e2e/send_token.cy.ts, packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx, packages/extension/src/components/pages/SignMessage/SignMessage.tsx
Fix the send payment when there are no funds
=> Fix the send payment when there are no funds

packages/extension/package.json, packages/extension/public/manifest.json, yarn.lock
Commits:
- [Release 2.8.0](https://github.com/GemWallet/gemwallet-extension/commit/72d4789c2e8e46df180f910f893ad35b82a348a9)
=> Release 2.8.0

packages/extension/cypress/e2e/send_token.cy.ts
Check transaction history after a transaction is successful
=> Check transactions history with Cypress

packages/api/src/sendPayment/sendPayment.ts, packages/constants/src/event/event.types.ts, packages/constants/src/message/message.types.ts, packages/constants/src/payload/payload.types.ts, packages/extension/cypress/e2e/payments.cy.ts, packages/extension/cypress/e2e/send_token.cy.ts, packages/extension/src/chromeServices/background.ts, packages/extension/src/chromeServices/content.ts, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/utils/parseFromString.ts
Make sendPayment retro-compatible between v2 and v3 of the API
=> Handle sendPayment retrocompatibility

packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx, packages/extension/src/components/pages/SignMessage/SignMessage.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/constants/apiErrors.ts, packages/extension/src/constants/index.ts
Send message to the API when there are errors within the UI
=> Feat/errors UI

packages/extension/src/components/organisms/Header/Header.tsx, packages/extension/src/components/pages/EditWallet/EditWallet.tsx, packages/extension/src/components/pages/ListWallets/Wallet/Wallet.tsx, packages/extension/src/utils/index.ts, packages/extension/src/utils/truncateWalletName.test.ts, packages/extension/src/utils/truncateWalletName.ts
Fix the issues from: https://github.com/GemWallet/gemwallet-extension/issues/187
=> Fix the issue with too long wallet name

packages/extension/src/components/molecules/NetworkIndicator/ErrorSwitchNetworkDialog/ErrorSwitchNetworkDialog.tsx, packages/extension/src/components/molecules/NetworkIndicator/ErrorSwitchNetworkDialog/index.ts, packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx, packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Conenct back to the previous network if the connection to a new network failed
=> Fix network connection handling

packages/extension/src/components/pages/History/History.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Add custom message if network is not connected within the tx history
=> Add custom message if network is not connected within the tx history

packages/api/src/index.ts, packages/api/src/on/index.ts, packages/api/src/on/on.ts, packages/api/templates/index.html, packages/constants/src/event/event.types.ts, packages/constants/src/message/message.types.ts, packages/constants/src/network/network.constant.ts, packages/constants/src/payload/payload.types.ts, packages/extension/cypress/e2e/NFT.cy.ts, packages/extension/cypress/e2e/networks.cy.ts, packages/extension/cypress/e2e/offers.cy.ts, packages/extension/cypress/e2e/payments.cy.ts, packages/extension/cypress/e2e/send_token.cy.ts, packages/extension/cypress/e2e/set_account.cy.ts, packages/extension/cypress/e2e/submit_transaction.cy.ts, packages/extension/cypress/e2e/trustlines.cy.ts, packages/extension/cypress/e2e/wallet_management.cy.ts, packages/extension/src/chromeServices/background/index.ts, packages/extension/src/chromeServices/background/utils/session.ts, packages/extension/src/chromeServices/content/index.ts, packages/extension/src/components/pages/ListWallets/ListWallets.tsx, packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/components/pages/Settings/Settings.tsx, packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Naming convention inspired by:
- https://docs.metamask.io/wallet/reference/provider-api/#events
- https://docs.web3js.org/guides/web3_providers_guide/events_listening/
=> Add events

packages/extension/src/components/pages/About/About.tsx
Change the description within the about page.
=> Change about description

packages/extension/src/hooks/useFees/useFees.test.ts, packages/extension/src/hooks/useFees/useFees.ts
Hotfix for an error of the useFees hook when calculating diff between balance and fees (not using drops).
Since this was already fixed in the submitTransactionsBulk PR, I have copied the code from there
=> Fix useFees hook

packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx, packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx, packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx, packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx, packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx, packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx, packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx, packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx, packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx, packages/extension/src/components/pages/MintNFT/MintNFT.tsx, packages/extension/src/components/pages/SetAccount/SetAccount.tsx, packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx, packages/extension/src/components/pages/Transaction/Transaction.tsx, packages/extension/src/hooks/useFees/useFees.ts, packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
Display to the UI when an account his not activated during an API transaction
=> Handle not activated account during an API transaction

packages/extension/src/components/pages/CreatePassword/CreatePassword.test.tsx, packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx, packages/extension/src/components/pages/Login/Login.test.tsx, packages/extension/src/components/pages/Login/Login.tsx
- **Password Input Enhancement:** Added an eye icon to the password input field during login, allowing users to toggle password visibility.
- **New Password Creation:** Incorporated a similar eye icon for creating new passwords, providing users with control over password visibility.
- **Error Message Clearing:** Improved user experience by automatically clearing error messages when users interact with the confirm password and new user password input fields.
=> Improve UX for password fields

packages/extension/cypress/e2e/trustlines.cy.ts, packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx, packages/extension/src/components/pages/AddNewTrustline/StepConfirm/StepConfirm.tsx, packages/extension/src/components/pages/AddNewTrustline/StepConfirm/index.ts, packages/extension/src/components/pages/AddNewTrustline/StepForm.tsx, packages/extension/src/components/pages/AddNewTrustline/StepForm/SearchToken/SearchToken.tsx, packages/extension/src/components/pages/AddNewTrustline/StepForm/SearchToken/index.ts, packages/extension/src/components/pages/AddNewTrustline/StepForm/StepForm.tsx, packages/extension/src/components/pages/AddNewTrustline/StepForm/index.ts, packages/extension/src/components/pages/AddNewTrustline/StepWarning/StepWarning.tsx, packages/extension/src/components/pages/AddNewTrustline/StepWarning/index.ts, packages/extension/src/components/pages/AddNewTrustline/TokenModal.tsx, packages/extension/src/components/pages/AddNewTrustline/index.ts, packages/extension/src/components/pages/Settings/Settings.tsx, packages/extension/src/constants/index.ts, packages/extension/src/constants/xrplmeta.ts, packages/extension/src/types/index.ts, packages/extension/src/types/xrplMeta.types.ts
You need to be on the mainnet to test it
=> Add token search bar

packages/extension/cypress/e2e/NFT.cy.ts, packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx, packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx, packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx, packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx, packages/extension/src/components/pages/MintNFT/MintNFT.tsx, packages/extension/src/contexts/LedgerContext/LedgerContext.tsx, packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.test.ts, packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.ts, packages/extension/src/utils/format.test.ts, packages/extension/src/utils/format.ts
Each commit corresponds to one view
=> Revamp NFT Transaction views

.vscode/settings.json, packages/extension/cypress/e2e/delete_account.cy.ts, packages/extension/cypress/e2e/offers.cy.ts, packages/extension/cypress/e2e/submit_raw_json_tx.cy.ts, packages/extension/src/components/atoms/KeyValueDisplay/KeyValueDisplay.tsx, packages/extension/src/components/molecules/TransactionDisplay/TransactionDisplay.tsx, packages/extension/src/components/molecules/TransactionHeader/TransactionHeader.tsx, packages/extension/src/components/pages/Login/Login.tsx, packages/extension/src/components/pages/SignMessage/SignMessage.tsx, packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/TransactionsDisplay.tsx, packages/extension/src/contexts/BrowserContext/BrowserContext.tsx, packages/extension/src/utils/NFTViewer.ts, packages/extension/src/utils/login.ts, packages/extension/src/utils/storageChromeLocal.ts
=> Cleanup code

.github/workflows/integration.yml, packages/extension/.gitignore, packages/extension/cypress/e2e/NFT.cy.ts, packages/extension/cypress/e2e/delete_account.cy.ts, packages/extension/cypress/e2e/hooks.cy.ts, packages/extension/cypress/e2e/networks.cy.ts, packages/extension/cypress/e2e/offers.cy.ts, packages/extension/cypress/e2e/payments.cy.ts, packages/extension/cypress/e2e/receive.cy.ts, packages/extension/cypress/e2e/send_token.cy.ts, packages/extension/cypress/e2e/set_account.cy.ts, packages/extension/cypress/e2e/set_regular_key.cy.ts, packages/extension/cypress/e2e/sign_transaction.cy.ts, packages/extension/cypress/e2e/submit_raw_json_tx.cy.ts, packages/extension/cypress/e2e/submit_transaction.cy.ts, packages/extension/cypress/e2e/submit_transactions_bulk.cy.ts, packages/extension/cypress/e2e/trustlines.cy.ts, packages/extension/cypress/e2e/wallet_management.cy.ts, packages/extension/cypress/e2e/xahau.cy.ts, packages/extension/cypress/utils/navigation.ts, packages/extension/package.json, yarn.lock
Extract cypress variable and fix the tests since the reset of the testnet
=> Extract Cypress
